export const SET_APPOINTMENTS = "SET_APPOINTMENTS";
export const SET_IS_FETCHING = "SET_IS_FETCHING";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";
export const SET_HOSPITAL = "SET_HOSPITAL";
