name: Functions Continuous Deployment

on:
  push:
    branches:
      - master
    paths:
      - "firebase/functions/**"
      - "packages/common/**"
  workflow_dispatch:
    inputs:
      version:
        description: "Commit to deploy to STG"
        required: false

jobs:
  functions_deployent_qa:
    name: Functions Staging Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Jerusalem
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn install
      - name: Write Test Service Account Key
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./test-service-account-key.json
          contents: ${{ secrets.TEST_SERVICE_ACCOUNT }}
          write-mode: overwrite
      - name: Build Common
        run: yarn workspace @zm-blood-components/common build
      - name: Install deployment dependencies
        run: npm i -g @rxdi/firelink firebase-tools

      - name: CD
        run: cd firebase/functions/

      - name: Deploy to Firebase Functions (Staging)
        run: firelink deploy --only functions:swapAppointment -P staging --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Test Functions
        run: yarn workspace @zm-blood-components/functions test
      - name: Deploy to Firebase Functions
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions -P staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
