name: Functions Production Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Functions commit to deploy"
        required: false

jobs:
  functions-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Jerusalem

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.version }}

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        run: yarn install

      - name: Build Functions
        run: yarn workspace @zm-blood-components/functions build

      - name: Write Test Service Account Key
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./test-service-account-key.json
          contents: ${{ secrets.TEST_SERVICE_ACCOUNT }}
          write-mode: overwrite

      - name: Install deployment dependencies
        run: npm i -g @rxdi/firelink

      - name: Run firelink
        working-directory: ./firebase/functions
        run: firelink --no-runner --leave-changes

      - name: Deploy to Firebase Functions (Production)
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions -P production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
